root = "."
tmp_dir = "../../tmp"
[build]
  bin = "../../tmp/tg_notifications"
  cmd = "go build -o ../../tmp/tg_notifications ./cmd/tg_notifications/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true 
